schema_version: 1

context:
  version: "0.20"

package:
  name: jbig2dec
  version: ${{ version }}

source:
  url: https://github.com/ArtifexSoftware/jbig2dec/releases/download/${{ version }}/jbig2dec-${{ version }}.tar.gz
  sha256: 7b63ff6470289547e7a3a0f145cb8ea6c2afffdd65645b7d87d3b7febc96fb3a

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cmake  # [win]
    - make
    - libtool  # [unix]
    - autoconf  # [unix]
    - automake  # [unix]
    - pkg-config
  host:
    - zlib
    - libpng
  run_exports:
    - ${{ pin_subpackage('jbig2dec', upper_bound='x.x') }}

tests:
  - script:
    - jbig2dec --help

about:
  homepage: https://jbig2dec.com/
  license: AGPL-3.0-only
  license_file: COPYING
  summary: 'A decoder implementation of the JBIG2 image compression format'
  description: |
    JBIG2 is designed for lossy or lossless encoding of 'bilevel'
    (1-bit monochrome) images at moderately high resolution, and
    in particular, scanned paper documents. In this domain it can
    be very efficient, offering compression ratios on the order of
    100:1

extra:
  recipe-maintainers:
    - scopatz
